[package]
name = "jos"
version = "0.1.0"

[dependencies]

[lib]
name = "jos"
edition = "2021"
path = "src/kernel.rs" 
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"