// http://kbdlayout.info/KBDGR/scancodes+names
static SCANCODES: [char; 69] = [
    0xfe as char,
    0xfe as char,
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '0',
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    'q',
    'w',
    'e',
    'r',
    't',
    'z',
    'u',
    'i',
    'o',
    'p',
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    'a',
    's',
    'd',
    'f',
    'g',
    'h',
    'j',
    'k',
    'l',
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    'y',
    'x',
    'c',
    'v',
    'b',
    'n',
    'm',
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
    0xfe as char,
];

pub fn get_key_for_scancode(scancode: u8) -> char {
    if scancode < 69 {
        SCANCODES[scancode as usize]
    } else {
        0xfe as char
    }
}
