name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  prepare:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker
        uses: docker/build-push-action@v5
        with:
          context: "buildenv_rust/"
          push: true
          tags: jbreu/jos:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build jos
        uses: addnab/docker-run-action@v3
        with:
          image: jbreu/jos:latest
          options: -v ${{ github.workspace }}:/root/env
          run: |
            . $HOME/.cargo/env
            make build-x86_64
