name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push docker
      uses: docker/build-push-action@v5
      with:
        context: buildenv_rust
        push: true
        tags: "jos/buildenv:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3